PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX gont: <https://gont.ch/> 


# Maps Event to HistoryMunicipality

INSERT { GRAPH <http://example.org/inference> {

  #?eventabolissionuri sem:hasActor ?histmunabolissionuri .
  #?eventadmissionuri sem:hasActor ?histmunadmissionuri .
  ?histmunabolissionuri gont:abolitionEvent ?eventabolissionuri .
  ?histmunadmissionuri gont:admissionEvent ?eventadmissionuri .

}}
WHERE { GRAPH <http://example.org/fso> {
  {
    ?eventabolissionuri a gont:MunicipalityChangeEvent ;
      gont:id ?eventid .
    
    ?histmunabolissionuri a gont:MunicipalityVersion ;
      eCH-0071:municipalityAbolitionNumber ?eventid ;

  } UNION # This UNION is necessary otherwise we lack half of the events
    {
    ?eventadmissionuri a gont:MunicipalityChangeEvent ;
      gont:id ?eventid .
    
    ?histmunadmissionuri a gont:MunicipalityVersion ;
      eCH-0071:municipalityAdmissionNumber ?eventid .
  }

}}