PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX gont: <https://gont.ch/> 


# Maps Event to DistrictEntityVersion

INSERT { GRAPH <http://example.org/inference> {

  #?eventabolissionuri sem:hasActor ?histdistabolissionuri .
  #?eventadmissionuri sem:hasActor ?histdistadmissionuri .
  ?histdistabolissionuri gont:abolitionEvent ?eventabolissionuri .
  ?histdistadmissionuri gont:admissionEvent ?eventadmissionuri .

}}
WHERE {
  {
    ?eventabolissionuri a gont:DistrictChangeEvent ;
      gont:id ?eventid .
    
    ?histdistabolissionuri a gont:DistrictEntityVersion ;
      eCH-0071:districtAbolitionNumber ?eventid ;

  }
    {
    ?eventadmissionuri a gont:DistrictChangeEvent ;
      gont:id ?eventid .
    
    ?histdistadmissionuri a gont:DistrictEntityVersion ;
      eCH-0071:districtAdmissionNumber ?eventid .
  }

}