PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX code: <http://data.admin.ch/id/code/ech-0071/>
PREFIX gont: <https://gont.ch/> 


# Map MunicipalityVersion to more specific classes

INSERT { GRAPH <http://example.org/inference> {
 # ?gemeinde a gont:PoliticalMunicipality .
  ?gemeindefrei a gont:MunicipalityFreeArea .
  ?seeanteil a gont:CantonalLakePortion .
}}
WHERE { GRAPH <http://example.org/fso> {
  # Politische Gemeinde
  #?gemeinde a gont:Municipality ;
   # eCH-0071:municipalityEntryModeId 11 .
  
  # Gemeindefreies Gebiet
  ?gemeindefrei a gont:Municipality ;
    eCH-0071:municipalityEntryModeId 12 .
  
   # Kantonaler Seeanteil
  ?seeanteil a gont:Municipality ;
    eCH-0071:municipalityEntryModeId 13 .

}}