PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX code: <http://data.admin.ch/id/code/ech-0071/>
PREFIX gont: <https://gont.ch/> 


# Map DistrictEntity to more specific classes

INSERT { GRAPH <http://example.org/inference> {
  ?district a gont:District .
  ?districtlesscanton a gont:DistrictlessCanton .
  ?districtfreearea a gont:DistrictFreeArea .
}}
WHERE { GRAPH <http://example.org/fso> {
  # Bezirk
  ?district a gont:DistrictEntity ;
    eCH-0071:districtEntryModeId 15 .
  
  # Kanton ohne Bezirksunterteilung
  ?districtlesscanton a gont:DistrictEntity ;
    eCH-0071:districtEntryModeId 16 .
  
   # Bezirksfreies Gebiet
  ?districtfreearea a gont:DistrictEntity ;
    eCH-0071:districtEntryModeId 17 .

}}