PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX gont: <https://gont.ch/> 

INSERT { GRAPH <http://example.org/inference> {
   ?munuri owl:sameAs ?sturi .
}}
WHERE
{ GRAPH <http://example.org/fso> {
   SERVICE <https://sparql.geo.admin.ch/sparql>
   {
      ?sturi a <http://schema.org/AdministrativeArea> ;
        rdfs:seeAlso ?munuri .
      #  <https://ld.geo.admin.ch/def/bfsNumber> ?municipalityId .
   }

   ?munuri a gont:Municipality .
    #  gont:id ?municipalityId .
}}