PREFIX rr:     <http://www.w3.org/ns/r2rml#>
PREFIX rml:    <http://semweb.mmlab.be/ns/rml#> 
PREFIX ql:     <http://semweb.mmlab.be/ns/ql#> 
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oslo:   <http://purl.org/oslo/ns/localgov#>
PREFIX adms:   <http://www.w3.org/ns/adms#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX vcard:  <http://www.w3.org/2006/vcard/ns#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX locn:    <http://www.w3.org/ns/locn#>
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX hgv: <http://data.admin.ch/def/hgv/> 


# Maps the mandatory fields to respective URIs
# Does not include Abolition entries as these are optional

CONSTRUCT {
  ?munuri eCH-0071:municipalityEntryMode ?municipalityEntryModeUri .
  ?munuri eCH-0071:municipalityAdmissionMode ?municipalityAdmissionModeUri .
}
WHERE {
  ?munuri a hgv:MunicipalityVersion;
    eCH-0071:municipalityEntryModeId ?municipalityEntryMode ;
    eCH-0071:municipalityAdmissionModeId ?municipalityAdmissionMode .
  
  ?municipalityEntryModeUri a skos:Concept ;
    skos:notation ?municipalityEntryMode .
  
  ?municipalityAdmissionModeUri a skos:Concept ;
    skos:notation ?municipalityAdmissionMode .
  
}
