PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX code: <http://data.admin.ch/id/code/ech-0071/>

# (1) Eingemeindung: [A] + [B] -> [A+]

## TODO das stimmt noch nicht, ist so nur Thurgau

#SELECT COUNT(*)
CONSTRUCT {
 ?eventuri a eCH-0071:EingemeindungEvent ;
}
WHERE {
  # Politische Gemeinde
  ?formermunuri a eCH-0071:HistoryMunicipality ;
    eCH-0071:municipalityAbolitionNumber  ?eventid ;
    eCH-0071:municipalityAbolitionModeId 26 ;
    eCH-0071:cantonAbbreviation ?canton ;
  eCH-0071:municipalityId ?formermunicipalityId .
 
  ?abandonnedmunuri a eCH-0071:HistoryMunicipality ;
    eCH-0071:municipalityAbolitionNumber  ?eventid ;
    eCH-0071:municipalityAbolitionModeId 29 ;
  eCH-0071:municipalityId ?abandonnedmunicipalityId .
    #eCH-0071:municipalityId 2242 .

  ?newmunuri a eCH-0071:HistoryMunicipality ;
    eCH-0071:municipalityAdmissionNumber ?eventid ;
    eCH-0071:municipalityAdmissionModeId 26 ;
    eCH-0071:municipalityId ?abandonnedmunicipalityId . ## TODO das muss admissionmunicipalityId werden
  
  ?eventuri a sem:Event ;
    eCH-0071:eventId ?eventid .
 
}