PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

# Maps Municipality to HistoryMunicipality

CONSTRUCT {
  ?eventuri sem:hasActor ?histmunuri
}
WHERE {
  ?histmunuri a eCH-0071:HistoryMunicipality ;
    eCH-0071:municipalityAdmissionNumber ?eventid .

  ?eventuri a sem:Event ;
    eCH-0071:eventId ?eventid .
}