PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX hgv: <http://data.admin.ch/def/hgv/> 

CONSTRUCT {
   ?munuri owl:sameAs ?dbpuri ;
}
WHERE
{
   SERVICE <http://dbpedia.org/sparql>
   {
     ?dbpuri dbo:country dbr:Switzerland ;
     dbp:municipalityCode ?municipalityId .
   }

   ?munuri a hgv:Municipality;
       hgv:id ?municipalityId .
# This should no longer be necessary as we do it on the Municipality, not on HistoryMunicipality
#   MINUS { ?munuri eCH-0071:municipalityAbolitionNumber ?municipalityAbolisionNumber . }

}