PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX hgv: <http://data.admin.ch/def/hgv/> 


# Maps Event to HistoryMunicipality

CONSTRUCT {

  #?eventabolissionuri sem:hasActor ?histmunabolissionuri .
  #?eventadmissionuri sem:hasActor ?histmunadmissionuri .
  ?histmunabolissionuri hgv:abolitionEvent ?eventabolissionuri .
  ?histmunadmissionuri hgv:admissionEvent ?eventadmissionuri .

}
WHERE {
  {
    ?eventabolissionuri a hgv:MunicipalityChangeEvent ;
      hgv:id ?eventid .
    
    ?histmunabolissionuri a hgv:MunicipalityVersion ;
      eCH-0071:municipalityAbolitionNumber ?eventid ;

  }
    {
    ?eventadmissionuri a hgv:MunicipalityChangeEvent ;
      hgv:id ?eventid .
    
    ?histmunadmissionuri a hgv:MunicipalityVersion ;
      eCH-0071:municipalityAdmissionNumber ?eventid .
  }

}