PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 

# Maps the status of the Municipality entry to a URI

CONSTRUCT {
  ?munuri eCH-0071:municipalityPredecessor ?oldmunuri .
  ?oldmunuri eCH-0071:municipalitySuccessor ?munuri .
}
WHERE {
  {
    ?munuri a eCH-0071:Municipality;
      eCH-0071:municipalityAdmissionNumber ?municipalityAdmissionNumber .
    MINUS { ?munuri eCH-0071:municipalityAbolitionNumber ?municipalityAbolisionNumber . }
    MINUS { ?munuri eCH-0071:municipalityAdmissionNumber 1000 . } 
  }
  ?oldmunuri  eCH-0071:municipalityAbolitionNumber ?municipalityAdmissionNumber .
}