PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 

# Maps Municipality to HistoryMunicipality

CONSTRUCT {
  ?munuri eCH-0071:historyMunicipality ?histmunuri .
  ?histmunuri eCH-0071:municipality ?munuri .
}
WHERE {
  ?histmunuri a eCH-0071:HistoryMunicipality ;
    eCH-0071:municipalityId ?municipalityId .

  ?munuri a eCH-0071:Municipality ;
    eCH-0071:municipalityId ?municipalityId .
}
