PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX schema: <http://schema.org/>
PREFIX eCH-0071: <http://www.ech.ch/xmlns/eCH-0071/1/> 
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

# Maps Event to HistoryMunicipality

CONSTRUCT {

  ?eventabolissionuri sem:hasActor ?histmunabolissionuri .
  ?eventadmissionuri sem:hasActor ?histmunadmissionuri .
  ?histmunabolissionuri eCH-0071:hasEvent ?eventabolissionuri .
  ?histmunadmissionuri eCH-0071:hasEvent ?eventadmissionuri .

}
WHERE {
  {
    ?eventabolissionuri a sem:Event ;
      eCH-0071:eventId ?eventid .
    
    ?histmunabolissionuri a eCH-0071:HistoryMunicipality ;
      eCH-0071:municipalityAbolitionNumber ?eventid ;

  }
    {
    ?eventadmissionuri a sem:Event ;
      eCH-0071:eventId ?eventid .
    
    ?histmunadmissionuri a eCH-0071:HistoryMunicipality ;
      eCH-0071:municipalityAdmissionNumber ?eventid .
  }

}